namespace Plants.Initializer;

internal static class NationalityFinder
{
    private static readonly Dictionary<string, Nationality> _isoToNationality = new()
    {
            { "AF", new Nationality("AF", "Afghanistan", "Afghan") },
            { "AL", new Nationality("AL", "Albania", "Albanian") },
            { "DZ", new Nationality("DZ", "Algeria", "Algerian") },
            { "AD", new Nationality("AD", "Andorra", "Andorran") },
            { "AO", new Nationality("AO", "Angola", "Angolan") },
            { "AR", new Nationality("AR", "Argentina", "Argentine") },
            { "AM", new Nationality("AM", "Armenia", "Armenian") },
            { "AU", new Nationality("AU", "Australia", "Australian") },
            { "AT", new Nationality("AT", "Austria", "Austrian") },
            { "AZ", new Nationality("AZ", "Azerbaijan", "Azerbaijani, Azeri") },
            { "BH", new Nationality("BH", "Bahrain", "Bahraini") },
            { "BD", new Nationality("BD", "Bangladesh", "Bengali") },
            { "BB", new Nationality("BB", "Barbados", "Barbadian") },
            { "BY", new Nationality("BY", "Belarus", "Belarusian") },
            { "BE", new Nationality("BE", "Belgium", "Belgian") },
            { "BZ", new Nationality("BZ", "Belize", "Belizean") },
            { "BJ", new Nationality("BJ", "Benin", "Beninese, Beninois") },
            { "BT", new Nationality("BT", "Bhutan", "Bhutanese") },
            { "BO", new Nationality("BO", "Bolivia", "Bolivian") },
            { "BW", new Nationality("BW", "Botswana", "Motswana, Botswanan") },
            { "BR", new Nationality("BR", "Brazil", "Brazilian") },
            { "BN", new Nationality("BN", "Brunei", "Bruneian") },
            { "BG", new Nationality("BG", "Bulgaria", "Bulgarian") },
            { "BF", new Nationality("BF", "Burkina Faso", "Burkinabe") },
            { "BI", new Nationality("BI", "Burundi", "Burundian") },
            { "CV", new Nationality("CV", "Cabo Verde", "Cabo Verdean") },
            { "KH", new Nationality("KH", "Cambodia", "Cambodian") },
            { "CM", new Nationality("CM", "Cameroon", "Cameroonian") },
            { "CA", new Nationality("CA", "Canada", "Canadian") },
            { "CF", new Nationality("CF", "Central African Republic", "Central African") },
            { "TD", new Nationality("TD", "Chad", "Chadian") },
            { "CL", new Nationality("CL", "Chile", "Chilean") },
            { "CO", new Nationality("CO", "Colombia", "Colombian") },
            { "KM", new Nationality("KM", "Comoros", "Comoran, Comorian") },
            { "CR", new Nationality("CR", "Costa Rica", "Costa Rican") },
            { "HR", new Nationality("HR", "Croatia", "Croatian") },
            { "CU", new Nationality("CU", "Cuba", "Cuban") },
            { "CY", new Nationality("CY", "Cyprus", "Cypriot") },
            { "DK", new Nationality("DK", "Denmark", "Danish") },
            { "DJ", new Nationality("DJ", "Djibouti", "Djiboutian") },
            { "DM", new Nationality("DM", "Dominica", "Dominican") },
            { "DO", new Nationality("DO", "Dominican Republic", "Dominican") },
            { "EC", new Nationality("EC", "Ecuador", "Ecuadorian") },
            { "EG", new Nationality("EG", "Egypt", "Egyptian") },
            { "SV", new Nationality("SV", "El Salvador", "Salvadoran") },
            { "GQ", new Nationality("GQ", "Equatorial Guinea", "Equatorial Guinean, Equatoguinean") },
            { "ER", new Nationality("ER", "Eritrea", "Eritrean") },
            { "EE", new Nationality("EE", "Estonia", "Estonian") },
            { "ET", new Nationality("ET", "Ethiopia", "Ethiopian") },
            { "FJ", new Nationality("FJ", "Fiji", "Fijian") },
            { "FI", new Nationality("FI", "Finland", "Finnish") },
            { "FR", new Nationality("FR", "France", "French") },
            { "GA", new Nationality("GA", "Gabon", "Gabonese") },
            { "GE", new Nationality("GE", "Georgia", "Georgian") },
            { "DE", new Nationality("DE", "Germany", "German") },
            { "GH", new Nationality("GH", "Ghana", "Ghanaian") },
            { "GI", new Nationality("GI", "Gibraltar", "Gibraltar") },
            { "GR", new Nationality("GR", "Greece", "Greek, Hellenic") },
            { "GD", new Nationality("GD", "Grenada", "Grenadian") },
            { "GT", new Nationality("GT", "Guatemala", "Guatemalan") },
            { "PG", new Nationality("PG", "Guinea", "Guinean") },
            { "GW", new Nationality("GW", "Guinea-Bissau", "Bissau-Guinean") },
            { "GY", new Nationality("GY", "Guyana", "Guyanese") },
            { "HT", new Nationality("HT", "Haiti", "Haitian") },
            { "HN", new Nationality("HN", "Honduras", "Honduran") },
            { "HU", new Nationality("HU", "Hungary", "Hungarian, Magyar") },
            { "IS", new Nationality("IS", "Iceland", "Icelandic") },
            { "IN", new Nationality("IN", "India", "Indian") },
            { "ID", new Nationality("ID", "Indonesia", "Indonesian") },
            { "IR", new Nationality("IR", "Iran", "Iranian, Persian") },
            { "IQ", new Nationality("IQ", "Iraq", "Iraqi") },
            { "IE", new Nationality("IE", "Ireland", "Irish") },
            { "IL", new Nationality("IL", "Israel", "Israeli") },
            { "IT", new Nationality("IT", "Italy", "Italian") },
            { "JM", new Nationality("JM", "Jamaica", "Jamaican") },
            { "JP", new Nationality("JP", "Japan", "Japanese") },
            { "JO", new Nationality("JO", "Jordan", "Jordanian") },
            { "KZ", new Nationality("KZ", "Kazakhstan", "Kazakhstani, Kazakh") },
            { "KE", new Nationality("KE", "Kenya", "Kenyan") },
            { "KI", new Nationality("KI", "Kiribati", "I-Kiribati") },
            { "KP", new Nationality("KP", "North Korea", "North Korean") },
            { "KW", new Nationality("KW", "Kuwait", "Kuwaiti") },
            { "KG", new Nationality("KG", "Kyrgyzstan", "Kyrgyzstani, Kyrgyz, Kirgiz, Kirghiz") },
            { "LA", new Nationality("LA", "Laos", "Lao, Laotian") },
            { "LV", new Nationality("LV", "Latvia", "Latvian, Lettish") },
            { "LB", new Nationality("LB", "Lebanon", "Lebanese") },
            { "LS", new Nationality("LS", "Lesotho", "Basotho") },
            { "LR", new Nationality("LR", "Liberia", "Liberian") },
            { "LY", new Nationality("LY", "Libya", "Libyan") },
            { "LI", new Nationality("LI", "Liechtenstein", "Liechtensteiner") },
            { "LT", new Nationality("LT", "Lithuania", "Lithuanian") },
            { "LU", new Nationality("LU", "Luxembourg", "Luxembourg, Luxembourgish") },
            { "MG", new Nationality("MG", "Madagascar", "Malagasy") },
            { "MW", new Nationality("MW", "Malawi", "Malawian") },
            { "MY", new Nationality("MY", "Malaysia", "Malaysian") },
            { "MV", new Nationality("MV", "Maldives", "Maldivian") },
            { "ML", new Nationality("ML", "Mali", "Malian, Malinese") },
            { "MT", new Nationality("MT", "Malta", "Maltese") },
            { "MH", new Nationality("MH", "Marshall Islands", "Marshallese") },
            { "MQ", new Nationality("MQ", "Martinique", "Martiniquais, Martinican") },
            { "MR", new Nationality("MR", "Mauritania", "Mauritanian") },
            { "MU", new Nationality("MU", "Mauritius", "Mauritian") },
            { "MX", new Nationality("MX", "Mexico", "Mexican") },
            { "MD", new Nationality("MD", "Moldova", "Moldovan") },
            { "MC", new Nationality("MC", "Monaco", "Monegasque, Monacan") },
            { "MN", new Nationality("MN", "Mongolia", "Mongolian") },
            { "ME", new Nationality("ME", "Montenegro", "Montenegrin") },
            { "MA", new Nationality("MA", "Morocco", "Moroccan") },
            { "MZ", new Nationality("MZ", "Mozambique", "Mozambican") },
            { "NA", new Nationality("NA", "Namibia", "Namibian") },
            { "NR", new Nationality("NR", "Nauru", "Nauruan") },
            { "NP", new Nationality("NP", "Nepal", "Nepali, Nepalese") },
            { "NL", new Nationality("NL", "Netherlands", "Dutch, Netherlandic") },
            { "NZ", new Nationality("NZ", "New Zealand", "New Zealand, NZ, Zelanian") },
            { "NI", new Nationality("NI", "Nicaragua", "Nicaraguan") },
            { "NE", new Nationality("NE", "Niger", "Nigerien") },
            { "NG", new Nationality("NG", "Nigeria", "Nigerian") },
            { "MP", new Nationality("MP", "Northern Mariana Islands", "Northern Marianan") },
            { "NO", new Nationality("NO", "Norway", "Norwegian") },
            { "OM", new Nationality("OM", "Oman", "Omani") },
            { "PK", new Nationality("PK", "Pakistan", "Pakistani") },
            { "PW", new Nationality("PW", "Palau", "Palauan") },
            { "PA", new Nationality("PA", "Panama", "Panamanian") },
            { "PG", new Nationality("PG", "Papua New Guinea", "Papua New Guinean, Papuan") },
            { "PY", new Nationality("PY", "Paraguay", "Paraguayan") },
            { "PE", new Nationality("PE", "Peru", "Peruvian") },
            { "PH", new Nationality("PH", "Philippines", "Filipino, Philippine") },
            { "PL", new Nationality("PL", "Poland", "Polish") },
            { "PT", new Nationality("PT", "Portugal", "Portuguese") },
            { "PR", new Nationality("PR", "Puerto Rico", "Puerto Rican") },
            { "QA", new Nationality("QA", "Qatar", "Qatari") },
            { "RO", new Nationality("RO", "Romania", "Romanian") },
            { "RU", new Nationality("RU", "Russia", "Russian") },
            { "RW", new Nationality("RW", "Rwanda", "Rwandan") },
            { "AS", new Nationality("AS", "Samoa", "Samoan") },
            { "SM", new Nationality("SM", "San Marino", "Sammarinese") },
            { "SA", new Nationality("SA", "Saudi Arabia", "Saudi, Saudi Arabian") },
            { "SN", new Nationality("SN", "Senegal", "Senegalese") },
            { "CS", new Nationality("CS", "Serbia", "Serbian") },
            { "SC", new Nationality("SC", "Seychelles", "Seychellois") },
            { "SL", new Nationality("SL", "Sierra Leone", "Sierra Leonean") },
            { "SG", new Nationality("SG", "Singapore", "Singapore, Singaporean") },
            { "SK", new Nationality("SK", "Slovakia", "Slovak") },
            { "SI", new Nationality("SI", "Slovenia", "Slovenian, Slovene") },
            { "SB", new Nationality("SB", "Solomon Islands", "Solomon Island") },
            { "SO", new Nationality("SO", "Somalia", "Somali") },
            { "ZA", new Nationality("ZA", "South Africa", "South African") },
            { "SS", new Nationality("SS", "South Sudan", "South Sudanese") },
            { "ES", new Nationality("ES", "Spain", "Spanish") },
            { "LK", new Nationality("LK", "Sri Lanka", "Sri Lankan") },
            { "SD", new Nationality("SD", "Sudan", "Sudanese") },
            { "SR", new Nationality("SR", "Suriname", "Surinamese") },
            { "SE", new Nationality("SE", "Sweden", "Swedish") },
            { "CH", new Nationality("CH", "Switzerland", "Swiss") },
            { "SY", new Nationality("SY", "Syria", "Syrian") },
            { "TJ", new Nationality("TJ", "Tajikistan", "Tajikistani") },
            { "TZ", new Nationality("TZ", "Tanzania", "Tanzanian") },
            { "TH", new Nationality("TH", "Thailand", "Thai") },
            { "TL", new Nationality("TL", "Timor-Leste", "Timorese") },
            { "TG", new Nationality("TG", "Togo", "Togolese") },
            { "TK", new Nationality("TK", "Tokelau", "Tokelauan") },
            { "TO", new Nationality("TO", "Tonga", "Tongan") },
            { "TN", new Nationality("TN", "Tunisia", "Tunisian") },
            { "TR", new Nationality("TR", "Turkey", "Turkish") },
            { "TM", new Nationality("TM", "Turkmenistan", "Turkmen") },
            { "TV", new Nationality("TV", "Tuvalu", "Tuvaluan") },
            { "UG", new Nationality("UG", "Uganda", "Ugandan") },
            { "UA", new Nationality("UA", "Ukraine", "Ukrainian") },
            { "AE", new Nationality("AE", "United Arab Emirates", "Emirati, Emirian, Emiri") },
            { "UY", new Nationality("UY", "Uruguay", "Uruguayan") },
            { "UZ", new Nationality("UZ", "Uzbekistan", "Uzbekistani, Uzbek") },
            { "VU", new Nationality("VU", "Vanuatu", "Ni-Vanuatu, Vanuatuan") },
            { "VE", new Nationality("VE", "Venezuela", "Venezuelan") },
            { "VN", new Nationality("VN", "Vietnam", "Vietnamese") },
            { "YE", new Nationality("YE", "Yemen", "Yemeni") },
            { "ZM", new Nationality("ZM", "Zambia", "Zambian") },
            { "ZW", new Nationality("ZW", "Zimbabwe", "Zimbabwean") },
    };

    public static Nationality? FindOrDefault(string isoCode) =>
        _isoToNationality.ContainsKey(isoCode)
            ? _isoToNationality[isoCode]
            : null;
}
