version: "3.3"
services:
  db:
    image: 'postgres:latest'
    ports:
      - 8001:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password1!
      POSTGRES_DB: plants
      PGDATA: var/lib/postgresql/data
    volumes:
      - ./db:/var/lib/postgresql/data

  migration:
    build: env
    environment:
      Migration:DbConnectionString: User ID=postgres;Password=password1!;Host=db;Port=5432;Database=plants;
    depends_on:
      - db
