version: "3.3"
services:
  db:
    image: 'postgres:latest'
    ports:
      - 8000:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password1!
      POSTGRES_DB: plants
      PGDATA: var/lib/postgresql/data
    volumes:
      - ./persist/db:/var/lib/postgresql/data
  
  eventstore:
    image: eventstore/eventstore:21.10.0-buster-slim
    environment:
      - EVENTSTORE_CLUSTER_SIZE=1
      - EVENTSTORE_RUN_PROJECTIONS=All
      - EVENTSTORE_START_STANDARD_PROJECTIONS=true
      - EVENTSTORE_EXT_TCP_PORT=1113
      - EVENTSTORE_HTTP_PORT=2113
      - EVENTSTORE_INSECURE=true
      - EVENTSTORE_ENABLE_EXTERNAL_TCP=true
      - EVENTSTORE_ENABLE_ATOM_PUB_OVER_HTTP=true
    ports:
      - "1113:1113"
      - "2113:2113"
    volumes:
      - ./persist/es/data:/var/lib/eventstore
      - ./persist/es/eslogs:/var/log/eventstore

  mongo:
    image: mongo:4.4.17
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password

    volumes:
      - ./persist/mongo:/data/db

  back:
    build: back/
    ports:
      - 8001:80
      - 5001:443
    environment:
      DbConnectionTemplate: Host=db;Database=plants;Username={0};Password={1}
      AllowedHosts: "*"
      Auth:AuthKey: "Set this key in secure configuration storage in prod mode"
      Auth:TokenValidityHours: 5000
      ASPNETCORE_URLS: "https://+;http://+"
      ASPNETCORE_HTTPS_PORT: 5001
      ASPNETCORE_Kestrel__Certificates__Default__Password: "password"
      ASPNETCORE_Kestrel__Certificates__Default__Path: /https/aspnetapp.pfx
    volumes:
      - ~/.aspnet/https:/https

    depends_on:
      - migration
      - eventstore

  front:
    build: front/
    ports:
      - 8002:80
    depends_on:
      - back