version: "3.3"
services:
  db:
    image: 'postgres:latest'
    ports:
      - 8000:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password1!
      POSTGRES_DB: plants
      PGDATA: var/lib/postgresql/data
    volumes:
      - ./persist/db:/var/lib/postgresql/data
      
  eventstore:
    image: eventstore/eventstore:22.10.0-buster-slim
    environment:
      - EVENTSTORE_CLUSTER_SIZE=1
      - EVENTSTORE_RUN_PROJECTIONS=All
      - EVENTSTORE_ENABLE_ATOM_PUB_OVER_HTTP=true
      - EVENTSTORE_HTTP_PORT=2113
      - EVENTSTORE_TRUSTED_ROOT_CERTIFICATES_PATH=/certs/ca
      - EVENTSTORE_CERTIFICATE_FILE=/certs/node1/node.crt
      - EVENTSTORE_CERTIFICATE_PRIVATE_KEY_FILE=/certs/node1/node.key
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl --fail --insecure https://node1.eventstore:2113/health/live || exit 1",
        ]
      interval: 5s
      timeout: 5s
      retries: 24
    ports:
      - 1111:1113
      - 2113:2113
    volumes:
      - ./persist/es/data:/var/lib/eventstore
      - ./persist/es/eslogs:/var/log/eventstore
      - ./persist/certs:/certs
    
  mongo:
    image: mongo:4.4.17
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=changeit
    volumes:
      - ./persist/mongo:/data/db