version: "3.3"
services:
    setup:
        image: eventstore/es-gencert-cli:1.0.2
        entrypoint: bash
        user: "1000:1000"
        command: >
          -c "mkdir -p ./certs && cd /certs
          && es-gencert-cli create-ca
          && es-gencert-cli create-node -out ./node1 -ip-addresses 127.0.0.1,172.30.240.11 -dns-names localhost
          && find . -type f -print0 | xargs -0 chmod 666"
        container_name: setup
        volumes:
          - ./persist/certs:/certs
 