version: "3.3"
services:
  db:
    image: 'postgres:latest'
    ports:
      - 8000:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password1!
      POSTGRES_DB: plants
      PGDATA: var/lib/postgresql/data
    volumes:
      - ./persist/db:/var/lib/postgresql/data

  eventstore:
    image: eventstore/eventstore:21.10.0-buster-slim
    environment:
      - EVENTSTORE_CERTIFICATE_FILE=/https/aspnetapp.pfx
      - EVENTSTORE_CERTIFICATE_PASSWORD=password
      - EVENTSTORE_CLUSTER_SIZE=1
      - EVENTSTORE_RUN_PROJECTIONS=All
      - EVENTSTORE_START_STANDARD_PROJECTIONS=true
      - EVENTSTORE_HTTP_PORT=2113
      - EVENTSTORE_ENABLE_ATOM_PUB_OVER_HTTP=true
      - EVENTSTORE_INSECURE=true
    ports:
      - "1113:1113"
      - "1115:1115"
      - "2113:2113"
    volumes:
      - ./persist/es/data:/var/lib/eventstore
      - ./persist/es/eslogs:/var/log/eventstore
      - ~/.aspnet/https:/https

  mongo:
    image: mongo:4.4.17
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password

    volumes:
      - ./persist/mongo:/data/db
