global using Plants.Domain;
global using Plants.Domain.Infrastructure;
global using Plants.Shared;
global using Plants.Aggregates;
global using Plants.Aggregates.Infrastructure;
global using Plants.Services;
global using Plants.Services.Infrastructure;
global using Plants.Files;
global using Plants.Files.Infrastructure;